# Stage 4 — Rentals, Payments and Analysis

# 4.1 Determine the total number of rentals.
SHOW FULL TABLES;
SELECT * FROM rental;

SELECT COUNT(rental_id) AS `number of all rentals`
FROM rental;


# 4.2 Determine which customer made the highest number of rentals.
SHOW FULL TABLES;
SELECT * FROM rental;

# how many rentals has each customer:
SELECT
	rental.customer_id,
	COUNT(rental_id) AS `number of rentals`
FROM rental
GROUP BY rental.customer_id;

# Solution using MAX, COUNT and VIEW:
CREATE VIEW rentals_per_customer AS
SELECT
	customer_id,
	COUNT(rental_id) AS 
    `number of rentals`
FROM rental
GROUP BY customer_id;

SELECT
    customer_id,
    `number of rentals`
FROM rentals_per_customer
WHERE `number of rentals` = (
    SELECT MAX(`number of rentals`)
    FROM rentals_per_customer);

# The solution below is incorrent because it returns two columns:
# one with all customers
# and the other with only one result - the highest number of rentals.
# SELECT
#    customer_id,
#    MAX(`number of rentals`)
# FROM rentals_per_customer;

# Solution using ORDER BY and LIMIT:
SELECT
	customer_id,
	COUNT(rental_id) AS `number of rentals`
FROM rental
GROUP BY customer_id
ORDER BY `number of rentals` DESC
LIMIT 0, 1;


# 4.3 Find the 10 customers who spent the most money.
SHOW FULL TABLES;
SELECT * FROM customer;
SELECT * FROM payment;

SELECT
	CONCAT(customer.first_name, ' ', customer.last_name) AS `customer`,
	SUM(payment.amount) AS `sum of all payments`
FROM payment
JOIN customer
	ON payment.customer_id = customer.customer_id
GROUP BY payment.customer_id
ORDER BY `sum of all payments`
LIMIT 0, 10;


# 4.4 Calculate the company's total revenue.
SHOW FULL TABLES;
SELECT * FROM payment;

SELECT
	SUM(amount) AS `total reveneu`
FROM payment;


# 4.5 Calculate the revenue generated by each store.
SHOW FULL TABLES;
SELECT * FROM payment;
SELECT * FROM staff;
SELECT * FROM store;
SELECT * FROM address;

SELECT
	address.address AS `address of store`,
    SUM(amount) AS `revenue generated by each store`
FROM payment
JOIN staff
	ON payment.staff_id = staff.staff_id
JOIN store
	ON staff.store_id = store.store_id
JOIN address
	ON store.address_id = address.address_id
GROUP BY payment.staff_id;


# 4.6 Determine which staff member processed the highest total payment amount.
SHOW FULL TABLES;
SELECT * FROM payment;
SELECT * FROM staff;

# Solution using ORDER BY and LIMIT:
SELECT
	CONCAT(staff.first_name, ' ', staff.last_name) AS `staff`,
	SUM(payment.amount) AS `total payment amount`
FROM payment
JOIN staff
	ON payment.staff_id = staff.staff_id
GROUP BY payment.staff_id
ORDER BY `total payment amount` DESC
LIMIT 0, 1;

# Solution using SUM(), MAX() and VIEW:
CREATE OR REPLACE VIEW total_payment_amount_processed_by_staff AS
SELECT
	CONCAT(staff.first_name, ' ', staff.last_name) AS `staff`,
	SUM(payment.amount) AS `total payment amount`
FROM payment
JOIN staff
	ON payment.staff_id = staff.staff_id
GROUP BY staff.first_name, staff.last_name;

DROP VIEW IF EXISTS total_payment_amount_processed_by_staff;

SELECT
	`staff`,
    `total payment amount`
FROM total_payment_amount_processed_by_staff
WHERE `total payment amount` =
	(SELECT
		MAX(`total payment amount`)
	FROM total_payment_amount_processed_by_staff);


# 4.7 Find the most frequently rented films.
SHOW FULL TABLES;
SELECT * FROM film;
SELECT * FROM inventory;
SELECT * FROM rental;

# Solution using ORDER BY and LIMIT:
SELECT
	film.title,
    COUNT(rental.rental_id) AS `number of rentals`
FROM film
JOIN inventory
	ON film.film_id = inventory.film_id
JOIN rental
	ON inventory.inventory_id = rental.inventory_id
GROUP BY film.film_id
ORDER BY `number of rentals` DESC
LIMIT 0 ,1;

# Solution using COUNT(), MAX() and VIEW:
CREATE OR REPLACE VIEW rentals_per_film AS
SELECT
	film.film_id,
    film.title,
    COUNT(rental.rental_id) AS `number of rentals`
FROM film
JOIN inventory
	ON film.film_id = inventory.film_id
JOIN rental
	ON inventory.inventory_id = rental.inventory_id
    GROUP BY film.film_id, film.title;

SELECT
	film_id,
    title,
    `number of rentals`
FROM rentals_per_film
WHERE `number of rentals` =
	(SELECT
		MAX(`number of rentals`)
	FROM rentals_per_film);


# 4.8 Find films that have never been rented.
SHOW FULL TABLES;
SELECT * FROM film;
SELECT * FROM inventory;
SELECT * FROM rental;

SELECT
    film.title,
    COUNT(rental.rental_id) AS `number of rentals`
FROM film
LEFT JOIN inventory
	ON film.film_id = inventory.film_id
LEFT JOIN rental
	ON inventory.inventory_id = rental.inventory_id
GROUP BY film.film_id
HAVING `number of rentals` = 0;

# How many films have never been rented:
CREATE OR REPLACE VIEW films_never_rented AS
SELECT
    film.title,
    COUNT(rental.rental_id) AS `number of rentals`
FROM film
LEFT JOIN inventory
	ON film.film_id = inventory.film_id
LEFT JOIN rental
	ON inventory.inventory_id = rental.inventory_id
GROUP BY film.film_id
HAVING `number of rentals` = 0;

DROP VIEW IF EXISTS film_never_rented;

SELECT
	COUNT(`number of rentals`) AS `number of films never rented`
FROM films_never_rented;


# 4.9 Determine the month with the highest revenue.
SHOW FULL TABLES;
SELECT * FROM payment;

SELECT
	MONTHNAME(payment_date) AS `month`,
	SUM(amount) AS `total amounts in determined month` 
FROM payment
GROUP BY `month`
ORDER BY `total amounts in determined month` DESC
LIMIT 0, 1;


# 4.10 Prepare a report showing: month → number of rentals → revenue.
SHOW FULL TABLES;
SELECT * FROM payment;
SELECT * FROM rental;

SELECT
	YEAR(rental.rental_date) AS `year`,
	MONTHNAME(rental.rental_date) AS `month`,
    COUNT(rental.rental_id) AS `number of rentals`,
	SUM(payment.amount) AS `total amounts in determined month` 
FROM payment
JOIN rental
	ON payment.rental_id = rental.rental_id
GROUP BY `year`, `month`;


