# Data Base Exploration
# Exploring INFORMATION_SCHEMA and MySQL system views

SELECT * FROM INFORMATION_SCHEMA.VIEWS
WHERE TABLE_SCHEMA = 'sakila';

SELECT TABLE_NAME
FROM INFORMATION_SCHEMA.VIEWS
WHERE TABLE_SCHEMA = 'sakila';

SELECT TABLE_NAME
FROM INFORMATION_SCHEMA.VIEWS;

SELECT *
FROM INFORMATION_SCHEMA.VIEWS;


USE information_schema;

# obiekty tabelopodobne
SHOW TABLES;
SHOW FULL TABLES;


DESC TABLES;
SHOW COLUMNS FROM TABLES;